services:
  postgres:
    container_name: smart_hire_postgres
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: smarthire
      POSTGRES_PASSWORD: smarthire1234
      POSTGRES_DB: smarthire
    volumes:
      - smart_hire_postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - smart_hire_network

  minio:
    container_name: smart_hire_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
      MINIO_BROWSER_REDIRECT_URL: "https://localhost:8900"
      MINIO_SERVER_URL: "https://localhost:9000"
    command: 'server /data/minio --console-address ":8900" --certs-dir /certs'
    volumes:
      - smart_hire_minio_data:/data
      - ./certs:/certs
    ports:
      - 8900:8900
      - 9000:9000
    networks:
      - smart_hire_network

  mailhog:
    container_name: smart_hire_mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - smart_hire_network

  redis:
    container_name: smart_hire_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - smart_hire_redis_data:/data
    networks:
      - smart_hire_network

volumes:
  smart_hire_postgres_data:
  smart_hire_minio_data:
  smart_hire_redis_data:

networks:
  smart_hire_network:
    driver: bridge
