services:
  postgres:
    container_name: smart_hire_postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: smarthire
      POSTGRES_PASSWORD: smarthire1234
      POSTGRES_DB: smarthire
    volumes:
      - smart_hire_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - smart_hire_network

  minio:
    container_name: smart_hire_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: 'minio server /data/minio --console-address ":8900"'
    volumes:
      - smart_hire_minio_data:/data

    ports:
      - 8900:8900
      - 9000:9000
    networks:
      - smart_hire_network

  mailhog:
    container_name: smart_hire_mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - smart_hire_network

volumes:
  smart_hire_postgres_data:
  smart_hire_minio_data:


networks:
  smart_hire_network:
    driver: bridge
